### ISSUE TITLE
Sub-collection and sub-manifest

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/presentation-builder#10]
@kerim1 

In the old version sub-collections and sub-manifests were reduced to id, label, type and thumbnail. I can not see this anymore. If I use setItems the whole collection will be shown.

**Comment by kerim1** [comment]
Can you show an example? For me this use case still works and has always worked. For instance: https://github.com/archival-IIIF/server/blob/master/src/builder/Metadata.ts#L17-L18

**Comment by Sozialarchiv** [comment]
I can not reproduce it anymore. Maybe it tested with the wrong version.
