### ISSUE TITLE
"Manifest V3" test broken

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/presentation-builder#5]
@kerim1 Your cleanup commit broke the "Manifest V3" test. Can you please fix that.

**Comment by kerim1** [comment]
@Sozialarchiv Yes, but I don't understand why. It doesn't show any difference between the two objects.

**Comment by Sozialarchiv** [comment]
There are differences. E.g the navDate:

"navDate": "1856-01-01T00:00:00Z",
"navDate": "1856-01-01T00:00:00.000Z",

**Comment by Sozialarchiv** [comment]
https://github.com/archival-IIIF/presentation-builder/commit/0f7b2a32c75aedf028b83932600a02d792c79585
